/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args) {

        Restaurant kfc = new Restaurant("kfc",5,"$$$");
        Restaurant mac = new Restaurant("mac",5,"$$");
        Review kfcReview1 = new Review("good restaurant","abdata",3);
        Review kfcReview2 = new Review("perfect restaurant","abdata",5);
        Review macReview1 = new Review("perfect restaurant","abdata",4);
        Review macReview2 = new Review("good restaurant","abdata",2);
        kfc.addReview(kfcReview1);
        kfc.addReview(kfcReview2);
        mac.addReview(macReview1);
        mac.addReview(macReview2);
        System.out.println(kfc.toString());
        System.out.println(mac.toString());

    }
}
