/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;


import java.io.*;
import java.nio.file.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Path path = Paths.get("C:\\Users\\STUDENT\\401pro\\java-fundamentals\\linter\\app\\src\\main\\resources\\gates.js");
        System.out.println(checkErr(path));
    }

    public static String checkErr(Path path) {

        String errMas = "";

        try {
            BufferedReader reader  = Files.newBufferedReader(path);
            String line = reader.readLine();
            int NumberOfLine = 1;
            while (line != null) {
                if (!line.endsWith(";") && !line.isEmpty() &&
                        !line.endsWith("{") && !line.endsWith("}") && !line.contains("if") && !line.contains("else")) {
//                     System.out.println("Line "+NumberOfLine+": Missing semicolon.");

                    errMas = errMas + "Line" + NumberOfLine + ": Missing semicolon.\n";
                }
                NumberOfLine++;
                line = reader.readLine();
            }

        } catch (IOException ex) {
            ex.printStackTrace();
        }

        return errMas;
    }
}


