/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test
    public void constructorTest() {
        Restaurant restaurantObject = new Restaurant("res", 3, "$");
        assertEquals("res", restaurantObject.getName() );
        assertEquals(3, restaurantObject.getNumOfStars());
        assertEquals("$", restaurantObject.getPriceCategory());
    }
    @Test
    public void restaurantToStringTest() {
        Restaurant restaurantObject = new Restaurant("res", 4, "$");
        Review abdReview1 = new Review("good","abd",4);
        restaurantObject.addReview( abdReview1);
        assertEquals("Restaurant{name='res', numOfStars=4* , priceCategory='$', review=[Review{body='good', author='abd', numOfStars=4}]}", restaurantObject.toString());
    }

    @Test
    public void RestuarantaddReviewTest() {
        Restaurant restaurantObject = new Restaurant("res", 3, "$");
        Review abdReview1 = new Review("good","abd",5);
        Review abdReview2 = new Review("good","abd",5);
        restaurantObject.addReview( abdReview1);
        restaurantObject.addReview( abdReview2);

        int numOfReviews = restaurantObject.getReviews().size();
        assertEquals(2, numOfReviews);
    }


//
    @Test public void RestuarantaverageRatingTest() {
        Restaurant restuarantObject = new Restaurant("res", 3, "$$");
        Review abdReview1 = new Review("good","abd",5);
        Review abdReview2 = new Review("good","abd",5);
        restuarantObject.addReview(abdReview1);
        restuarantObject.addReview(abdReview2);
        restuarantObject.averageReview();
        assertEquals(5, restuarantObject.getNumOfStars());
    }
    @Test
    public void testReview_constructor() {
        Review reviewObject = new Review( "good", "abd",5);
        assertEquals("Review{body='good', author='abd', numOfStars=5}",reviewObject.toString());
    }

    @Test
    public void reveiewToStringTest() {
        Review reviewObject = new Review( "good", "abd",5);
        assertEquals("Review{body='good', author='abd', numOfStars=5}",reviewObject.toString());

    }
}
